FROM python:3.13-slim

# Work from a root directory
WORKDIR /src

# Copy the requirements from the app folder
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the actual app folder INTO the /src/app directory
COPY ./app ./app
COPY ./tests ./tests

EXPOSE 7999

# Start using the module path "app.main:app"
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:7999", "app.main:app"]